# Generated by Django 4.1.7 on 2023-03-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_schemas.datatype'),
        ),
    ]
