# Generated by Django 4.1.7 on 2023-03-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0003_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(max_length=50),
        ),
    ]
